### ISSUE TITLE
Empty likers() collection

### ISSUE THREAD

**Issue by hasnatbabur** [overtrue/laravel-like#19]
// likers count
$post->likers;

The likers count always returning empty collection!

However overwriting writing the relation method like this works fine:
```
public function likers()
    {
        return $this->morphToMany(User::class, 'likable', 'likes');
    }
```

It is working well in laravel-follow used branch. Please help!

**Comment by overtrue** [comment]
Plz show me more context, thanks.

**Comment by hasnatbabur** [comment]
@overtrue actually I was using the 'laravel-follow' packages for liking models. But later decided using this plugin so that followers table remain clean and scalable.

So out-of-the box I noticed the likers() relationship method in CanBeLiked trait is different than the parent 'laravel-follow' one. And always returns empty related collections.

from 'laravel-like' Overtrue\LaravelLike\Traits\CanBeLiked
```
<?php

/**
     * Return followers.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function likers()
    {
        return $this->belongsToMany(config('auth.providers.users.model'), config('like.likes_table'), 'likable_id', config('like.user_foreign_key'))
            ->where('likable_type', static::class);
    }
```

the parent 'laravel-follow' likers relationship method from file 

```
/**
     * Return followers.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function likers()
    {
        return $this->morphToMany(config('follow.user_model'), config('follow.morph_prefix'), config('follow.followable_table'))
                    ->wherePivot('relation', '=', Follow::RELATION_LIKE)
                    ->withPivot('followable_type', 'relation', 'created_at');
    }
```

Yes suddenly 'laravel-like' likers relation changed from morphToMany to belongsToMany. And I beleive in 'laravel-like' it always return empty related users because of this part '->where('likable_type', static::class);' the  likable_type is expected to be value from ->getMorphClass() but direct class name used in query.

I had to rewrite the likers relation method like following to make it work correctly:
```
    /**
     * Return likers.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function likers()
    {
        return $this->morphToMany(User::class, 'likable', 'likes');
    }
```
But still a issue in the package. Please let me know if I was able to clear. Thanks

**Comment by overtrue** [comment]
@hasnatbabur It's my mistake, I'v fixed it, plz upgrade to new version.
