### ISSUE TITLE
How can I delete if likable_type or likable_id doesn't exist

### ISSUE THREAD

**Issue by ShekhSaifuddin007** [overtrue/laravel-like#21]
Here you can see my discussions table I deleted some discussion

![discussion](https://user-images.githubusercontent.com/48278861/78581616-eb181a00-7855-11ea-9197-5562a5ab5f5d.PNG)

and my likes table still have their type and id but I want that when I delete any discussion It will automatically delete the record from likes table how can I do that.?

![likes](https://user-images.githubusercontent.com/48278861/78581726-13077d80-7856-11ea-81bb-c7a8687db760.PNG)

**Comment by overtrue** [comment]
Sorry, polymorphic associations can't be deleted by association.

**Comment by overtrue** [comment]
You can listen the Model::deleted event and delete the relations.

**Comment by ShekhSaifuddin007** [comment]
Yeah Thank you problem solved.
