### ISSUE TITLE
How can other then User model can be Liker?

### ISSUE THREAD

**Issue by Hussam3bd** [overtrue/laravel-like#25]
Hi,
I'm running into an issue where I have a ``Page`` model that can like something.
but unfortunately, as I noticed the Liker can only be the user model.

Any suggestion?

**Comment by overtrue** [comment]
Sorry, currently only the User model can be used.

**Comment by overtrue** [comment]
Hi @Hussam3bd plz upgrade to 4.0.0 to support this feature. https://github.com/overtrue/laravel-like/releases/tag/4.0.0
