### ISSUE TITLE
Method Illuminate\Database\Eloquent\Collection::likes does not exist. When trying to count the number of likes

### ISSUE THREAD

**Issue by JamieCee20** [overtrue/laravel-like#28]
On my blade page I have {{ $post->likes()->count() }} to display the number of current likes however when I refresh the page I get the error: Method Illuminate\Database\Eloquent\Collection::likes does not exist.

To my understanding Im not using that so unsure why it wont find the function im looking for.

Any help would be appreciated.

Jamie

**Comment by overtrue** [comment]
Plz show me the controller code.

JamieCee20 <notifications@github.com>于2020年7月30日 周四下午11:04写道：

**Comment by JamieCee20** [comment]
/**
     * Display the specified resource.
     *
     * @param  \App\Verified  $verified
     * @return \Illuminate\Http\Response
     */
    public function show(Verified $verified)
    {
        $user = User::find($verified->user_id);
        return view('verifieds.show', compact('user','verified'));
    } 

This is in my post Controller

**Comment by overtrue** [comment]
So, $post is undefined?

JamieCee20 <notifications@github.com>于2020年7月31日 周五上午1:06写道：

**Comment by JamieCee20** [comment]
No I have it as $verified->likers() - >count()

**Comment by overtrue** [comment]
Plz, explain where is the `$post` defined?  paste the controller code and blade template code.

**Comment by JamieCee20** [comment]
So Due to the way my project pans out, $verified is my post. This is my controller

    /**
     * Display the specified resource.
     *
     * @param  \App\Verified  $verified
     * @return \Illuminate\Http\Response
     */
    public function show(Verified $verified)
    {
        $user = User::find($verified->user_id);
        return view('verifieds.show', compact('user','verified'));
    }

And my blade was like this:

<div class="row">
                            <div class="ml-3 pt-3">
                                <span class="like-btn d-flex">
                                    <a class="likeButton" href="{{$user->toggleLike($verified)}}"><i class="fas fa-thumbs-up mr-2"></i></a><div>{{$verified->likers()->count()}}</div> 
                                </span>
                            </div>
                        </div>

**Comment by JamieCee20** [comment]
And my blade was like this:

<a class="likeButton" href="{{  $user->toggleLike($verified)  }}"><i class="fas fa-thumbs-up mr-2"></i></a><div>{{  $verified->likers()->count()  }}</div>

**Comment by overtrue** [comment]
Hi, @JamieCee20, I read your code, this error is impossible because `$verified` will always be an instance of `Verified `. So please double check your logic to see if there is a variable overwrite.

**Comment by JamieCee20** [comment]
Verified is still posts and doesnt overrun anywhere. I have Post which is user posts but verified is the same functionality just for verified Users, (May be a less complicated scenario but im still very new to laravel).

**Comment by JamieCee20** [comment]
So surely if I set my controller to $post = Verified::find({id}) then it will still be the same outcome?

**Comment by JamieCee20** [comment]
/**
     * Display the specified resource.
     *
     * @param  \App\Verified  $verified
     * @return \Illuminate\Http\Response
     */
    public function show(Verified $verified)
    {
        $user = User::find($verified->user_id);
        $likes = $user->likes()->with('likeable')->paginate(20);
        return view('verifieds.show', compact('user','verified', 'likes'));
    }

This is my controller, verifieds is just a different post so imagine all $verified is $post. 

My show.blade.php has this 

                                    @foreach($likes as $Like)
                                        {{$like->likeable}}
                                    @endforeach

to display my information. 

and the error I get is Class name must be a valid object or a string
