### ISSUE TITLE
How to get user Like on post collection?

### ISSUE THREAD

**Issue by MonMohon** [overtrue/laravel-like#30]
$posts = Post::with('post_images')->with('user')->withCount('comments')->orderBy('created_at', 'desc')->get();

how to get total likes for each post?

thank you

**Comment by overtrue** [comment]
```
$posts = Post::with('post_images')->with('user')->withCount(['comments', 'likers'])->orderBy('created_at', 'desc')->get();
```

**Comment by MonMohon** [comment]
ok thank you

**Comment by MonMohon** [comment]
and also how to use for laravel-follow

$posts = Post::with('post_images')->with('user')->withCount(['comments', 'likers'])->orderBy('created_at', 'desc')->get();

**Comment by overtrue** [comment]
Just using the relation name `followers`

**Comment by overtrue** [comment]
$posts = Post::with('post_images')->with('user')->withCount(['comments', 'likers', 'followers'])->orderBy('created_at', 'desc')->get();

**Comment by MonMohon** [comment]
thank you so much

**Comment by MonMohon** [comment]
one last favor

how to use hasLiked on this collection

$user = Auth::id();
$posts = Post::with('post_images')->with('user')->withCount(['comments', 'likers'])->orderBy('created_at', 'desc')->get();

**Comment by MonMohon** [comment]
sorry got it
with('likers')
