### ISSUE TITLE
Can i like a user by using other user? 

### ISSUE THREAD

**Issue by bsormagec** [overtrue/laravel-like#31]
It Returns an error when i try to do this. Can you tell me a way to use it @overtrue

**Comment by overtrue** [comment]
plz paste the error message and show me your code.

**Comment by bsormagec** [comment]
![image](https://user-images.githubusercontent.com/965219/102823605-4130eb80-43ec-11eb-86c7-0747628df518.png)

`Trait method likes has not been applied, because there are collisions with other trait methods on App\Models\User`

@overtrue

**Comment by overtrue** [comment]
Hi @bsormagec  plz upgrade to 4.0.0 to support this feature. https://github.com/overtrue/laravel-like/releases/tag/4.0.0

**Comment by bsormagec** [comment]
> Hi @bsormagec plz upgrade to 4.0.0 to support this feature. https://github.com/overtrue/laravel-like/releases/tag/4.0.0

Thank you @overtrue this issue fixed

**Comment by overtrue** [comment]
You're welcome.
