### ISSUE TITLE
Likes Count Issue

### ISSUE THREAD

**Issue by zpreston123** [overtrue/laravel-like#34]
After upgrading the package from 2.0 to 4.0, the following error displayed in the post index view:

<img width="1266" alt="Screen Shot 2021-02-25 at 8 03 21 PM" src="https://user-images.githubusercontent.com/11165740/109240109-e11c4400-77a4-11eb-8d8e-5483620f9a7b.png">

Querying the posts via Laravel as follows:
```php
$posts = Post::withCount('likes')
            ->whereIn('user_id', function ($query) {
                $query->select('following_id')
                    ->from('user_follower')
                    ->where('follower_id', auth()->id());
            })->orWhere('user_id', auth()->id())
            ->latest()
            ->paginate(10);
```

Created like button as a Vue component to display the count and update it when a post is liked or unliked.

The count from the Post model is fetched via "likes_count" attribute.

Issue appears to be a bug in the package.

**Comment by overtrue** [comment]
yes, it's a breaking change. try to use `likers` instead.

**Comment by zpreston123** [comment]
Fixed it by replacing "likes" with "likers" in withCount() method.

Then, replaced "likes()" method with "likers()" method in the "getLikesCountAttribute()" accessor method within the Post model:

```php
    /**
     * Get the number of likes on a post.
     *
     * @return int
     */
    public function getLikesCountAttribute(): int
    {
        return $this->likes()->count();
    }
```

All set, thanks for the help.

**Comment by overtrue** [comment]
﻿You are welcome.

发自我的iPhone
