### ISSUE TITLE
Disable un-published migration

### ISSUE THREAD

**Issue by zombozo12** [overtrue/laravel-like#48]
Hi, can you delete this line of code on purpose only published migration that can be migrated?

https://github.com/overtrue/laravel-like/blob/ce780746169d5a784af284bf35a19335ee5b935f/src/LikeServiceProvider.php#L23

Thank you.

**Comment by jnbn** [comment]
Did you know that this was a breaking change for all users "who was loading and migrating from Service provider registered migrations"  to force-publish as all tests started to fail after new version?
