### ISSUE TITLE
Error Publishing Migrations and Config

### ISSUE THREAD

**Issue by iamsubingyawali** [overtrue/laravel-like#49]
This package doesn't seem to create or publish migrations in my Laravel 9 installation. 

The command `php artisan vendor:publish --provider="Overtrue\\LaravelLike\\LikeServiceProvider" --tag=migrations` throws a warning: `No publishable resources for tag [migrations].`

The warning is the same for `--tag=configs` as well.

Also, I might be wrong, but the package doesn't create a default likes table migration which I can use. Do I have to manually create a likes table or is the package supposed to create a default migration for me?

**Comment by overtrue** [comment]
remove the tag option and try again

**Comment by iamsubingyawali** [comment]
Same error `No publishable resources for tag []`

**Comment by overtrue** [comment]
Windows?

**Comment by iamsubingyawali** [comment]
Yes

Windows 11
Laravel 9

**Comment by overtrue** [comment]
@iamsubingyawali Plz uses the following command and select the target resources:

```php
php artisan vendor:publish
```

**Comment by iamsubingyawali** [comment]
I couldn't find any providers relating to laravel-like

**Comment by iamsubingyawali** [comment]
Works this way. Thanks! ❣️
