### ISSUE TITLE
like posts by company instead of user 

### ISSUE THREAD

**Issue by IslamHeza** [overtrue/laravel-like#55]
hello
In my app the user has a company profile in addition to the his profile ( like Facebook pages).
I need to like a Post by this company profile using company_id for example. 
How to implement that with your package please ?
thanks

**Comment by jdesousa1** [comment]
Hi @IslamHeza,

1.- Add "Liker" trait to Company model

`
class Company 
{
    use Liker;

    <...>
}
`

2.- Add "Likeable" trait to Post model

`
class Post
{
    use Likeable;

    <...>
}
`

3.- Done, you can attach likes by company. For example:

```
$company = Company::find($company_id);
$post = Post::find($post_id);

$company->like($post);
$company->unlike($post);
$company->toggleLike($post);
```

PD: You can use Liker trait to User model.

Please, implement it and let us know something.

**Comment by IslamHeza** [comment]
Yes, I tried this before, but now my problem is getting all the post likers grouped by liker type. Also, this may duplicate the liker_id (user_id).

For example:
User ID = 5 liked post ID 1.
>> This adds a new row to the "likers" table with liker_id = 5 and likable_id = 1.
then if company ID = 5 liked the same post,
>> This will add a new row to the table with liker_id = 5 and post_id = 1 again.

Now we have two separate models who have liked the post.

Is there any way to figure out the type of each liker? like the "likable_type" .

**Comment by overtrue** [comment]
@IslamHeza Hello, maybe you should use this package? https://github.com/overtrue/laravel-follow
