### ISSUE TITLE
Likes relationship

### ISSUE THREAD

**Issue by kuvallini** [overtrue/laravel-like#66]
I would recommend to add likes relationship: 

    public function likes(): \Illuminate\Database\Eloquent\Relations\MorphMany
    {
        return $this->morphMany(config('like.like_model'), 'likeable');
    }

In the same way as you did in Favorites. It is useful for delete all linked likes to the object, etc.

**Comment by overtrue** [comment]
@kuvallini https://github.com/overtrue/laravel-like/blob/master/src/Traits/Liker.php#L83-L87 did you see this?

**Comment by kuvallini** [comment]
huh, thank you for such wonderful package

**Comment by kuvallini** [comment]
huh, thank you for such wonderful package
