### ISSUE TITLE
某个用户 like 的数据、分页获取，可否获取文章的用户信息？

### ISSUE THREAD

**Issue by hedeqiang** [overtrue/laravel-like#8]
单独获取 某篇文章，这样是可以获取到用户信息的
```
$likers = $post->likers()->paginate(20);

foreach($likers as $user) {
    // echo $user->name;
}
```

但是我如果 Get user likes with pagination:
```
$likes = $user->likes()->with('likable')->paginate(20);

foreach ($likes as $like) {
    $like->likable; // App\Post instance
}
```
这种方式好像没有办法获取用户的详细信息，超哥是否有其他的方法？

**Comment by overtrue** [comment]
后者明明是拿用户喜欢的对象列表，和用户信息有什么关系？

hedeqiang <notifications@github.com>于2019年6月13日 周四下午6:29写道：

**Comment by hedeqiang** [comment]
@overtrue    是的，但是可以获取 post 的信息、并不能获取这个 post 对应人的信息

**Comment by overtrue** [comment]
那和这个包没关系啊，那是你 post 模型的事情

hedeqiang <notifications@github.com>于2019年6月13日 周四下午6:59写道：

**Comment by hedeqiang** [comment]
嗯，好的，我就是想 post 肯定存的是 user_id ,比如昵称、头像之类的肯定没有保存到 post 中
